apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service--teste-hpa
  namespace: service--teste
  labels:
    app: service--teste
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service--teste
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50