apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: service--teste-kustomization
  namespace: service--teste
resources:
  - service.yaml
  - deployment.yaml
  - horizontalPodScaling.yaml
  - secrets.yaml
  - namespace.yaml