apiVersion: v1
kind: Service
metadata:
  name: service--teste-service
  namespace: service--teste
spec:
  type: ClusterIP
  selector:
   app: service--teste
  ports:
    - port: 5000
      name: main-http-5000
      protocol: TCP
      targetPort: 5000